# Generated by Django 4.1.4 on 2023-09-06 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kicksal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='cup_manager',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='unidade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unidade', to='kicksal.unidade'),
        ),
    ]
