# Generated by Django 4.1.4 on 2023-09-06 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kicksal', '0002_remove_unidade_cup_manager_alter_funcionario_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campeonato',
            name='quadra',
        ),
    ]
