# Generated by Django 4.1.4 on 2023-09-06 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kicksal', '0004_alter_jogador_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='time',
            unique_together={('nome', 'campeonato')},
        ),
    ]
