# Generated by Django 4.1.4 on 2023-09-06 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kicksal', '0005_alter_time_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='quadra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kicksal.quadra'),
        ),
    ]
