# Generated by Django 4.1.4 on 2023-09-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kicksal', '0006_jogo_quadra'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='time',
            constraint=models.UniqueConstraint(condition=models.Q(('posicao__gt', 0)), fields=('campeonato', 'posicao'), name='unique_position'),
        ),
    ]
