# Generated by Django 4.1.4 on 2023-09-22 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kicksal', '0007_time_unique_position'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='time',
            name='unique_position',
        ),
        migrations.RemoveField(
            model_name='time',
            name='posicao',
        ),
    ]
