# Generated by Django 4.1.4 on 2023-10-29 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kicksal', '0008_remove_time_unique_position_remove_time_posicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time', to='kicksal.time'),
        ),
    ]
